import type { ResearchModuleId } from "../contracts/research-contracts.js";
import { ENGINEERING_DECISIONS, RESEARCH_PLUGIN_PHASES } from "../plugin-goals.js";

export function buildResearchPluginSummary() {
  return {
    pluginId: "research-plugin",
    strategy: "plugin-first",
    currentStage: "phase-5-execution-backed-vtkjs-eval",
    decisions: [...ENGINEERING_DECISIONS],
    registeredModules: [
      "paper_search",
      "knowledge_ingest",
      "vtkjs_knowledge_ingest",
      "vtkjs_retrieve_context",
      "vtkjs_generation_brief",
      "vtkjs_code_generate",
      "vtkjs_eval_runner",
      "rag_query",
      "context_pack_build",
      "knowledge_store_status",
      "research_vtkjs_loop",
      "vtkjs_template_select",
      "phase5_agent_exec_recipe",
      "vtkjs_render_verify",
      "vtkjs_repair_once",
      "phase5_local_workflow_plan",
      "phase5_repair_workflow_plan",
      "research_phase5_execution_loop",
      "research_phase5_repair_loop",
      "research_phase5_visualization_loop",
      "sandbox_policy_decide",
      "docker_sandbox_run",
      "cloud_sandbox_plan",
      "phase3_local_workflow_plan",
      "phase3_agent_exec_recipe",
      "artifact_capture",
      "task_graph_snapshot",
      "trace_replay",
      "structured_progress_updates",
      "task_graph_summary",
      "canvas_bridge",
      "task_flow_bridge",
      "vtk_scene_export",
      "paper_ingest",
      "task_orchestrator",
      "code_generator",
      "sandbox_run",
      "validator",
      "trace_recorder",
      "report_build",
      "vtkjs_validate",
    ] satisfies ResearchModuleId[],
    phases: RESEARCH_PLUGIN_PHASES.map((phase) => ({
      id: phase.id,
      title: phase.title,
    })),
    nextMilestones: [
      "Turn research_vtkjs_loop into the single long-term entrypoint for vtk.js planning, generation, validation, repair, and eval after the new specialized retrieval layer",
      "Replace local paper fixtures with Arxiv, Crossref, or Scholar adapters",
      "Swap the new vtk.js keyword retrieval layer for vector search plus rerank",
      "Connect research_phase5_execution_loop to richer vtk.js knowledge retrieval instead of local-only routing heuristics",
      "Expand execution-backed vtk.js benchmark coverage from scaffold scenes to richer task-specific scene logic",
      "Wire Phase 5 repair review payloads into real Dashboard or Canvas surfaces",
    ],
  };
}
